# Generated by Django 4.2.1 on 2023-05-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0002_alter_historicaldata_adj_close_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'verbose_name': 'Historical Data', 'verbose_name_plural': 'Historical Data'},
        ),
    ]
