# Generated by Django 4.2.1 on 2023-06-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_source', '0004_remove_instrument_id_alter_instrument_ticker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
