# Generated by Django 4.2.1 on 2023-05-14 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('czk', 'CZK')], default='usd', max_length=3)),
                ('initial_balance', models.FloatField(default=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Portfolio',
                'verbose_name_plural': 'User Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WIDTHRAWAL', 'Widthrawal'), ('DIVIDEND', 'Dividend')], default=None, max_length=32)),
                ('symbol', models.CharField(max_length=10)),
                ('trans_units', models.BigIntegerField()),
                ('trans_date', models.DateField()),
                ('trans_price', models.FloatField()),
                ('commision', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
