# Generated by Django 4.2.1 on 2023-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolio_portfolio_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='open_positions',
            field=models.JSONField(default=dict),
        ),
    ]
